import { useState } from 'react';
import { ArrowRight, ClipboardCopy, Database, FileJson, Info, Search, Shield, TerminalSquare } from 'lucide-react';
import { Link } from 'react-router-dom';
import { DomainLabel, DownloadButton, EmptyState, formatTimestamp, Outcome, Panel, SectionHeading, StatusDot } from '../components/Common';
import { downloadJSON, IS_DEMO } from '../services/api';
import type { Run } from '../types/sentinel';

export function IncidentsPage({ runs }: { runs: Run[] }) {
  const [query, setQuery] = useState('');
  const findings = runs.flatMap((run) => run.events.filter((event) => event.decision !== 'allow').map((event) => ({ run, event })))
    .filter(({ run, event }) => `${run.id} ${run.scenario} ${event.tool} ${event.reasonCodes.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page-stack"><SectionHeading title="Incidents" description="An investigation queue built from recorded defense interventions." />
    <div className="notice notice--info"><Info size={16} />Interventions are leads for investigation. A blocked action is not automatically an attack, and an escalation is not automatically a policy violation.</div>
    <Panel title="Security findings" action={<div className="inline-search inline-search--small"><Search size={15} /><input aria-label="Search findings" placeholder="Search findings..." value={query} onChange={(e) => setQuery(e.target.value)} /></div>}>
      {findings.length === 0 ? <EmptyState title="No matching findings" description="Try a wider time range or change your search." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Run</th><th>Action</th><th>Decision</th><th>Reason codes</th><th>Recorded</th><th /></tr></thead><tbody>
        {findings.map(({ run, event }) => <tr key={event.id}><td><Link className="table-link" to={`/runs/${run.id}`}>{run.id}</Link></td><td><strong className="mono">{event.tool}</strong><div className="table-secondary">{event.description}</div></td>
          <td><StatusDot status={event.decision} /></td><td className="reason-cell">{event.reasonCodes.slice(0, 2).map((code) => <code key={code}>{code}</code>)}</td><td>{formatTimestamp(event.occurredAt)}</td>
          <td><Link to={`/runs/${run.id}`} className="table-open" aria-label={`Open ${run.id}`}><ArrowRight size={16} /></Link></td></tr>)}
      </tbody></table></div>}
    </Panel>
  </div>;
}

const sampleRequest = {
  user_goal: 'Summarize ticket TCK-501',
  candidate_action: { type: 'tool_call', tool: 'ticket_read', arguments: { ticket_id: 'TCK-501' } },
  policy_context: { allowed_tools: ['ticket_read'], confirmation_required_tools: [] },
};
export function PlaygroundPage() {
  const [value, setValue] = useState(JSON.stringify(sampleRequest, null, 2));
  const [result, setResult] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [working, setWorking] = useState(false);
  const run = async () => {
    try {
      const parsed = JSON.parse(value) as unknown;
      setError(null);
      if (IS_DEMO) { setResult(null); setError('Demo mode does not execute defense decisions. Set VITE_DASHBOARD_MODE=api and connect a dashboard backend to run tests.'); return; }
      setWorking(true);
      const response = await fetch('/api/playground', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(parsed) });
      if (!response.ok) throw new Error(`Playground API returned HTTP ${response.status}`);
      setResult(JSON.stringify(await response.json(), null, 2));
    } catch (err) { setResult(null); setError(err instanceof Error ? err.message : 'Could not process the request.'); }
    finally { setWorking(false); }
  };
  return <div className="page-stack"><SectionHeading title="Playground" description="Prepare and inspect synthetic candidate actions before submitting them to the defense." />
    <div className="notice notice--info"><Info size={16} />No synthetic decision is generated by the frontend. Real testing requires the dashboard backend to expose POST /api/playground.</div>
    <div className="summary-grid"><Panel title="Candidate action"><p className="panel-subtitle">Edit a synthetic input. The backend will need to complete the official DefenseRequest fields.</p>
      <textarea className="code-editor" value={value} onChange={(e) => setValue(e.target.value)} aria-label="Candidate action JSON" spellCheck={false} />
      <div className="button-row"><button type="button" className="button button--primary" disabled={working} onClick={run}><TerminalSquare size={16} />{working ? 'Running...' : 'Validate / run'}</button><button className="button button--light" type="button" onClick={() => { setValue(JSON.stringify(sampleRequest, null, 2)); setResult(null); setError(null); }}>Reset</button></div>
    </Panel>
    <Panel title="Result"><p className="panel-subtitle">The dashboard never guesses ALLOW, BLOCK, ESCALATE or REWRITE.</p>
      {error && <div className="notice notice--error">{error}</div>}
      {result ? <pre className="json-box json-box--large">{result}</pre> : <EmptyState title="Awaiting execution" description="Connect the backend to evaluate this candidate action." />}
    </Panel></div></div>;
}

export function ArtifactsPage({ runs }: { runs: Run[] }) {
  return <div className="page-stack"><SectionHeading title="Data & Artifacts" description="Export saved run records and normalized decision traces." action={<DownloadButton label="Export all runs" onClick={() => downloadJSON('sentinel-runs.json', runs)} />} />
    <Panel title="Available run exports"><p className="panel-subtitle">These are normalized frontend records. Original simulator JSONL artifacts remain on disk. This view exports redacted normalized records.</p>
      {runs.length === 0 ? <EmptyState title="No artifacts in range" description="Change the global time range to find older runs." /> : <div className="artifact-list">{runs.map((run) => <div className="artifact-row" key={run.id}>
        <FileJson size={25} className="artifact-icon" /><div><strong>{run.id.toLowerCase()}.json</strong><p><DomainLabel domain={run.domain} /> · {run.events.length} actions · {run.scenario}</p></div>
        <Outcome outcome={run.outcome} /><button className="button button--light" type="button" onClick={() => downloadJSON(`${run.id.toLowerCase()}.json`, run)}>Download</button>
      </div>)}</div>}
    </Panel></div>;
}

export function SettingsPage() {
  const [density, setDensity] = useState(() => window.localStorage.getItem('sentinel-density') === 'compact' ? 'compact' : 'comfortable');
  const [copied, setCopied] = useState(false);
  const applyDensity = (next: string) => {
    setDensity(next); window.localStorage.setItem('sentinel-density', next);
    document.documentElement.dataset.density = next;
  };
  const copy = async () => { try { await navigator.clipboard.writeText('GET /api/dashboard → DashboardData'); setCopied(true); } catch { setCopied(false); } };
  return <div className="page-stack"><SectionHeading title="Settings" description="Local dashboard preferences and integration status." />
    <div className="summary-grid"><Panel title="Appearance"><div className="settings-block"><strong>Table density</strong><p>Choose the spacing used by the trace and results tables.</p>
      <div className="segmented-control" role="group" aria-label="Table density"><button type="button" className={density === 'comfortable' ? 'segmented-control__active' : ''} onClick={() => applyDensity('comfortable')}>Comfortable</button><button type="button" className={density === 'compact' ? 'segmented-control__active' : ''} onClick={() => applyDensity('compact')}>Compact</button></div>
      <div className="settings-preference"><Shield size={20} /><span>Cloudflare-inspired light design · dot-and-text decision statuses</span></div></div></Panel>
    <Panel title="Data connection"><div className="settings-block"><div className="connection-state"><span className={`connection-led ${IS_DEMO ? 'connection-led--demo' : ''}`} />{IS_DEMO ? 'Illustrative demo data' : 'Dashboard API mode'}</div>
      <p>{IS_DEMO ? 'The app is displaying local fixtures. No simulator, model or defense is currently connected.' : 'The frontend is loading records from the configured dashboard backend.'}</p>
      <div className="settings-endpoint"><Database size={17} /><code>GET /api/dashboard</code><button type="button" aria-label="Copy API contract" onClick={copy}><ClipboardCopy size={15} /></button>{copied && <small>Copied</small>}</div>
      <p className="help-copy">Set VITE_DASHBOARD_MODE=api in .env and run the bundled read-only dashboard backend. Restart Vite after changing environment variables.</p></div></Panel></div>
  </div>;
}
