"""Centralized reason codes used across the defense. Only emit a code when the module
responsible for it actually found the evidence it names."""

NOT_A_TOOL_CALL = "NOT_A_TOOL_CALL"
POLICY_TOOL_NOT_ALLOWED = "POLICY_TOOL_NOT_ALLOWED"
POLICY_PREREQUISITE_MISSING = "POLICY_PREREQUISITE_MISSING"
MISSING_CONFIRMATION = "MISSING_CONFIRMATION"

UNTRUSTED_INSTRUCTION_SOURCE = "UNTRUSTED_INSTRUCTION_SOURCE"
UNTRUSTED_ARGUMENT_ORIGIN = "UNTRUSTED_ARGUMENT_ORIGIN"
AUTHORITY_MISMATCH = "AUTHORITY_MISMATCH"

GOAL_MISMATCH = "GOAL_MISMATCH"
USER_GOAL_ALIGNED = "USER_GOAL_ALIGNED"

SENSITIVE_DATA_FLOW = "SENSITIVE_DATA_FLOW"
SECRET_TO_EXTERNAL_SINK = "SECRET_TO_EXTERNAL_SINK"
ENCODED_SECRET_DETECTED = "ENCODED_SECRET_DETECTED"

MEMORY_POISONING_RISK = "MEMORY_POISONING_RISK"
UNTRUSTED_MEMORY_SOURCE = "UNTRUSTED_MEMORY_SOURCE"

MULTISTEP_RISK = "MULTISTEP_RISK"

HIGH_IMPACT_ACTION = "HIGH_IMPACT_ACTION"
SAFE_REWRITE_AVAILABLE = "SAFE_REWRITE_AVAILABLE"
REWRITE_UNSAFE = "REWRITE_UNSAFE"

LOW_RISK_READ = "LOW_RISK_READ"

HIGH_RISK = "HIGH_RISK"
MODERATE_RISK = "MODERATE_RISK"
